export type StudentMemberType = "Normal" | "Core" | "Base"

export type Student = {
  id: string
  name: string
  grade: string
  major: string
  semester: string
  isPaid: boolean
  paymentDate: string
  receiptName: string
  teacherName: string
  courses: Course[]
  referrer: string
  referrerRate: number
  closer: string
  closerRate: number
  memberType: StudentMemberType
  isTeamMember?: boolean
}

export type Course = {
  id: string
  name: string
  type: string
  semester: string
  totalHours: number
  attendedHours: number
  hourlyRate: number
  totalCost: number
  isPaid: boolean
  teacherName: string
  teacherTierIndex: number
  teacherBaseCost: number
  additionalTeachers?: { name: string; cost: number }[]
  projectTag: string
  paymentDate?: string
  selected?: boolean
  editHours?: number
  editRate?: number
  assignedTeacher?: string
  assignedTierIndex?: number
  assignedCost?: number
}

export type Teacher = {
  id: string
  name: string
  gradSchool: string
  rankPos: string
  rankTotal: string
  tierIndex: number
  customBaseSalary: string
}

export type TeacherRecord = {
  id: string
  syncId?: string // Add syncId for binding course consumption with cost records
  teacherName: string
  courseName: string
  courseType: string
  projectTag: string
  gradSchool: string
  majorRank: string
  baseTierIndex: number
  evalBonus: number
  scoreBonus: number
  baseHourlyCost: number
  performanceCost: number
  attendedHours: number
  totalCost: number
  date: string
  account: string
  status: string
  handler: string
  payee: string
  infoUpdateTime: string
  isAutoGenerated?: boolean
  isBonusSettlement?: boolean
  abstract?: string
}

export type Expense = {
  id: string
  date: string
  payee: string
  reason: string
  amount: number
  category: string
  account: string
  status: string
  projectTag: string
  linkStudentId?: string
  linkSemester?: string
}

export type BonusRule = {
  id: string
  personName: string
  projectTag: string
  ratio: number
  type: string
}

export type PresetCourse = {
  name: string
  type: string
  hours: number
  rate: number
  defaultTeacher?: string
  defaultCost?: number
}

export type PresetData = {
  [major: string]: {
    [grade: string]: {
      [semester: string]: PresetCourse[]
    }
  }
}

export type TeacherTier = {
  label: string
  base: number
}

export type School = {
  name: string
  tier: number
}

export type LegacyStudent = {
  id: string
  name: string
  grade: string
  major: string
  isTeamMember?: boolean
  courses: LegacyCourse[]
}

export type LegacyCourse = {
  id: string
  name: string
  type: string
  teacherName: string
  totalHours: number
  hourlyRate: number
  totalCost: number
  teacherBaseCost: number
  teacherTierIndex: number
  isPaid: boolean
  paymentDate?: string
  receiptName?: string
  attendedHours: number
  isFinished: boolean
  semester: string
  projectTag: string
  additionalTeachers?: { name: string; cost: number }[]
}

export type LegacyData = {
  students?: LegacyStudent[]
  teachers?: Teacher[]
  teacherCosts?: TeacherRecord[]
  expenses?: Expense[]
  bonusRules?: BonusRule[]
  coursePresets?: PresetData
  initialBalance?: number
}

export type CoursePreset = {
  major: string
  grade: string
  semester: string
  courses: PresetCourse[]
}
